version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "laminar"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-plzznz0puqz4"
s3_prefix = "laminar"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
